truncate table customer       ;
truncate table district       ;
truncate table history        ;
truncate table item           ;
truncate table new_orders     ;
truncate table order_line     ;
truncate table orders         ;
truncate table stock          ;
truncate table warehouse      ;
